"""Generate src/core/elements.c from the desktop tables.

The desktop Periodic_table.py and ionic_bonding_calculator.py stay the single
source of truth: the Python port (chemptab.py) and this C table are both built
from them, so the three cannot drift apart.
"""
import io
import os
import sys
from decimal import Decimal, ROUND_HALF_UP

# Work the paths out from this file, so the script runs wherever the
# repository happens to sit - including on a build machine.
HERE = os.path.dirname(os.path.abspath(__file__))
ADDIN = os.path.dirname(HERE)
MODULES = os.path.dirname(ADDIN)
sys.path.insert(0, os.path.join(MODULES, "chemistry-calculator"))

from Periodic_table import ELEMENTS
from ionic_bonding_calculator import ELECTRONEGATIVITIES as EN

IB_SPELLING = {"aluminum": "aluminium", "cesium": "caesium"}
BOOKLET = {"S": "32.07"}          # the IB data booklet value
NO_EN = ("He", "Ne", "Ar")        # no Pauling value is defined

rows = []
for z, symbol, name, weight in ELEMENTS:
    name = IB_SPELLING.get(name, name).capitalize()
    mass = BOOKLET.get(
        symbol,
        str(Decimal(repr(weight)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)))
    en = EN.get(symbol)
    en = 0.0 if (en is None or symbol in NO_EN or en == 0.0) else en
    rows.append((z, symbol, name, mass, en))

out = io.StringIO()
out.write("""/* elements.c - the periodic table.
 *
 * GENERATED by test/gen_elements.py from the desktop calculator's tables;
 * edit that script, not this file.
 *
 * en == 0 means no electronegativity is tabulated for that element.
 */

#include "chem.h"

const chem_element_t chem_elements[CHEM_ELEMENT_COUNT] = {
""")
for z, symbol, name, mass, en in rows:
    out.write('    {"%s", "%s", %sf, %.2ff},%s\n'
              % (symbol, name, mass, en, "" if z % 10 else "   /* Z=%d */" % z))
out.write("};\n")

path = os.path.join(ADDIN, "src", "core", "elements.c")
io.open(path, "w", encoding="ascii", newline="\n").write(out.getvalue())
print("wrote %s (%d elements)" % (path, len(rows)))
